apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/k3s-argocd-gitops
    targetRevision: HEAD
    path: manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
